services:
  catalogdb:
    image: postgres:18
    environment:
      POSTGRES_DB: catalogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - catalog_data:/var/lib/postgresql

  catalogservice:
    build:
      context: .
      dockerfile: src/CatalogContext/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=catalogdb;Database=catalogdb;Username=postgres;Password=pass
      - ConnectionStrings__RabbitMqConnection=rabbitmq://guest:pass@rabbitmq
    depends_on:
      - catalogdb
      - rabbitmq
  
  orderingdb:
    image: postgres:18
    environment:
      POSTGRES_DB: orderingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - ordering_data:/var/lib/postgresql

  orderingservice:
    build:
      context: .
      dockerfile: src/OrderingContext/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=orderingdb;Database=orderingdb;Username=postgres;Password=pass
      - ConnectionStrings__RabbitMqConnection=rabbitmq://guest:pass@rabbitmq
    depends_on:
      - orderingdb
      - rabbitmq

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: pass

volumes:
  catalog_data:
  ordering_data: